language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm run test:unit
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
